### ISSUE TITLE
NO and IT  langs not included in v1.1.1 npm package

### ISSUE THREAD

**Issue by MattieBelt** [sourcecode911/i18n-nationality#26]
Altho `it` and `no` are [in the source code](https://github.com/sourcecode911/i18n-nationality/tree/master/langs) they aren't publish to npm.

**Steps to reproduce:**
```bash
npm init -y
npm install i18n-nationality
ls node_modules/i18n-nationality/langs # de.json  en.json  fr.json
```

**Comment by msegers** [comment]
+1, seems like the latest code is not published, but the previous version with a new version number?
